
ALL_COMMISSIONS = [

# ES  CONTINUOUS E-MINI S&P 500 CONTRACT
{'commission': 4.0, 'margin': 6160.0, 'mult': 50.0, 'name': 'ES'},
# CL  CONTINUOUS CRUDE OIL CONTRACT
{'commission': 4.0, 'margin': 2695.0, 'mult': 1000.0, 'name': 'CL'},
# TY  CONTINUOUS 10 YR US TREASURY NOTE CONTRACT
{'commission': 4.0, 'margin': 990.0, 'mult': 1000.0, 'name': 'TY'}, #AKA ZN
# NQ  CONTINUOUS E-MINI NASDAQ 100 CONTRACT
{'commission': 4.0, 'margin': 6380.0, 'mult': 20.0, 'name': 'NQ'},
# EU  CONTINUOUS EURO FX CONTRACT
{'commission': 4.0, 'margin': 2310.0, 'mult': 125000.0, 'name': 'EU'}, # AKA 6E
# GC  CONTINUOUS GOLD CONTRACT
{'commission': 4.0, 'margin': 3000.0, 'mult': 100.0, 'name': 'GC'},
# FV  CONTINUOUS 5 YR US TREASURY NOTE CONTRACT
{'commission': 4.0, 'margin': 616.0, 'mult': 1000.0, 'name': 'FV'}, # AKA ZF
# YM  CONTINUOUS E-MINI DOW JONES $5 CONTRACT
{'commission': 4.0, 'margin': 5390.0, 'mult': 5.0, 'name': 'YM'},
# US  CONTINUOUS 30 YR US TREASURY BOND CONTRACT
{'commission': 4.0, 'margin': 2365.0, 'mult': 1000.0, 'name': 'US'}, # AKA ZB
# JY  CONTINUOUS JAPANESE YEN CONTRACT
{'commission': 4.0, 'margin': 2200.0, 'mult': 125000.0, 'name': 'JY'}, # AKA 6J
# BP  CONTINUOUS BRITISH POUND CONTRACT
{'commission': 4.0, 'margin': 1980.0, 'mult': 62500.0, 'name': 'BP'}, #AKA 6B
# AD  CONTINUOUS AUSTRALIAN DOLLAR CONTRACT
{'commission': 4.0, 'margin': 1375.0, 'mult': 100000.0, 'name': 'AD'}, # AKA 6A
# NG  CONTINUOUS NATURAL GAS CONTRACT
{'commission': 4.0, 'margin': 1320.0, 'mult': 10000.0, 'name': 'NG'},
# TU  CONTINUOUS 2 YR US TREASURY NOTE CONTRACT
{'commission': 4.0, 'margin': 418.0, 'mult': 200000.0, 'name': 'TU'}, #AKA ZT
# CD  CONTINUOUS CANADIAN DOLLAR CONTRACT
{'commission': 4.0, 'margin': 1210.0, 'mult': 100000.0, 'name': 'CD'}, #AKA 6C
# C   CONTINUOUS CORN CONTRACT
{'commission': 4.0, 'margin': 792.0, 'mult': 50.0, 'name': 'C'}, #AKA C
# SI  CONTINUOUS SILVER CONTRACT
{'commission': 4.0, 'margin': 4000.0, 'mult': 5000.0, 'name': 'SI'},
# HG  CONTINUOUS COPPER CONTRACT
{'commission': 4.0, 'margin': 3000.0, 'mult': 25000.0, 'name': 'HG'},
# S   CONTINUOUS SOYBEANS CONTRACT
{'commission': 4.0, 'margin': 2035.0, 'mult': 50.0, 'name': 'S'}, #AKA ZS
# UB  CONTINUOUS ULTRA US TREASURY BOND CONTRACT
{'commission': 4.0, 'margin': 3410.0, 'mult': 1000.0, 'name': 'UB'}, #AKA TN
# LG  CONTINUOUS LONG GILT CONTRACT
{'commission': 4.0, 'margin': 2178.0, 'mult': 100000.0, 'name': 'LG'}, #AKA GLTL
# NN  CONTINUOUS NIKKEI 225 YEN INDEX CONTRACT
{'commission': 4.0, 'margin': 5720.0, 'mult': 5.0, 'name': 'NN'}, # AKA NKD
# W   CONTINUOUS WHEAT CONTRACT
{'commission': 4.0, 'margin': 1485.0, 'mult': 50.0, 'name': 'W'}, #AKA ZW
# SF  CONTINUOUS SWISS FRANC CONTRACT
{'commission': 4.0, 'margin': 3080.0, 'mult': 125000.0, 'name': 'SF'}, # AKA 6S
# HO  CONTINUOUS NEW YORK HARBOR ULSD CONTRACT
{'commission': 4.0, 'margin': 3200.0, 'mult': 4.2, 'name': 'HO'},
# EMD CONTINUOUS E-MINI S&P MIDCAP 400 CONTRACT
# RB  CONTINUOUS RBOB GASOLINE CONTRACT
{'commission': 4.0, 'margin': 3795.0, 'mult': 42000.0, 'name': 'RB'},
# DX  CONTINUOUS US DOLLAR INDEX CONTRACT
{'commission': 4.0, 'margin': 1815.0, 'mult': 1000.0, 'name': 'DX'},
# BO  CONTINUOUS SOYBEAN OIL CONTRACT
{'commission': 4.0, 'margin': 660.0, 'mult': 6000.0, 'name': 'BO'}, #AKA ZL
# SB  CONTINUOUS SUGAR #11 WORLD CONTRACT
{'commission': 4.0, 'margin': 1047.0, 'mult': 1120.0, 'name': 'SB'}, #AKA
# PX  CONTINUOUS MEXICAN PESO CONTRACT
{'commission': 4.0, 'margin': 1265.0, 'mult': 500000.0, 'name': 'PX'},#AKA 6M
# SM  CONTINUOUS SOYBEAN MEAL CONTRACT
{'commission': 4.0, 'margin': 1815.0, 'mult': 100.0, 'name': 'SM'},#AKA ZM
# NE  CONTINUOUS NEW ZEALAND DOLLAR CONTRACT
{'commission': 4.0, 'margin': 1430.0, 'mult': 100000.0, 'name': 'NE'}, #AKA 6N
# TN  CONTINUOUS ULTRA 10 YR US TREASURY NOTE CONTRACT
# VX  CONTINUOUS CBOE VOLATILITY INDEX (VIX) CONTRACT
# NKD CONTINUOUS NIKKEI 225 DOLLAR INDEX CONTRACT
# KC  CONTINUOUS COFFEE CONTRACT
{'commission': 4.0, 'margin': 2310.0, 'mult': 375.0, 'name': 'KC'},
# PL  CONTINUOUS PLATINUM CONTRACT
{'commission': 4.0, 'margin': 1650.0, 'mult': 50.0, 'name': 'PL'},
# RTY CONTINUOUS E-MINI RUSSELL 2000 CONTRACT
# SS  CONTINUOUS MSCI SINGAPORE INDEX CONTRACT
# ED  CONTINUOUS EURODOLLAR CONTRACT
# XT  CONTINUOUS 10 YR AUSTRALIAN T BOND CONTRACT
# CT  CONTINUOUS COTTON #2 CONTRACT
# KW  CONTINUOUS HARD RED WINTER WHEAT CONTRACT
{'commission': 4.0, 'margin': 1850.0, 'mult': 50.0, 'name': 'KW'}, #AKA KE
# CC  CONTINUOUS COCOA CONTRACT
{'commission': 4.0, 'margin': 2090.0, 'mult': 10.0, 'name': 'CC'},
# HE  CONTINUOUS LEAN HOGS CONTRACT
{'commission': 4.0, 'margin': 1320.0, 'mult': 400.0, 'name': 'HE'},
# LE  CONTINUOUS LIVE CATTLE CONTRACT
{'commission': 4.0, 'margin': 1650.0, 'mult': 400.0, 'name': 'LE'},
# PA  CONTINUOUS PALLADIUM CONTRACT
{'commission': 4.0, 'margin': 8250.0, 'mult': 100.0, 'name': 'PA'},
# QW  CONTINUOUS WHITE SUGAR CONTRACT
# RS  CONTINUOUS CANOLA CONTRACT
# QC  CONTINUOUS LONDON COCOA CONTRACT
# GF  CONTINUOUS FEEDER CATTLE CONTRACT
{'commission': 4.0, 'margin': 3080.0, 'mult': 500.0, 'name': 'GF'},
# MW  CONTINUOUS HARD RED SPRING WHEAT CONTRACT
# LRC CONTINUOUS ROBUSTA COFFEE CONTRACT
# OJ  CONTINUOUS ORANGE JUICE - A CONTRACT
{'commission': 4.0, 'margin': 1249.0, 'mult': 150.0, 'name': 'OJ'},
# KPO CONTINUOUS CRUDE PALM OIL CONTRACT
# FN  CONTINUOUS NATURAL GAS BALANCING POINT CONTRACT
# MXE CONTINUOUS MDAX CONTRACT
# TA  CONTINUOUS STOXX EUROPE 600 BANKS CONTRACT
# SQ  CONTINUOUS STOXX EUROPE 50 INDEX CONTRACT
# FF  CONTINUOUS 30 DAY FED FUND CONTRACT
# STS CONTINUOUS STOXX EUROPE 600 BASIC RESOURCES CONTRACT
# CCM CONTINUOUS BRAZILIAN YELLOW CORN CONTRACT
# RR  CONTINUOUS ROUGH RICE CONTRACT
{'commission': 4.0, 'margin': 1210.0, 'mult': 12.5, 'name': 'RR'},#AKA ZR
# O   CONTINUOUS OATS CONTRACT
{'commission': 4.0, 'margin': 742.0, 'mult': 12.5, 'name': 'O'},#AKA ZO
# LB  CONTINUOUS RANDOM LENGTH LUMBER CONTRACT
{'commission': 4.0, 'margin': 1760.0, 'mult': 110.0, 'name': 'LB'},
# IR  CONTINUOUS 90 DAY BANK ACCEPTED BILL CONTRACT
# SEE CONTINUOUS STOXX EUROPE 600 OIL & GAS CONTRACT
# NCB CONTINUOUS ULTRA 10YR NOTE- T BOND CONTRACT
# BGI CONTINUOUS LIVE CATTLE CONTRACT
# DIJ CONTINUOUS 1 DAY BANK DEPOSITS CONTRACT
# ICF CONTINUOUS ARABICA COFFEE 4/5 CONTRACT
# TEX CONTINUOUS 10YR NOTE- ULTRA 10 YR NOTE 3:2 CONTRACT
# UX  CONTINUOUS EUA CONTRACT
# IHO CONTINUOUS HEATING OIL CONTRACT
{'commission': 4.0, 'margin': 3520.0, 'mult': 42000.0, 'name': 'IHO'}, #AKA HO
# BR  CONTINUOUS BRAZILIAN REAL CONTRACT

]