

ALL_ETF_PAIRS = [
    ['FNGD', 'FNGU'],
    ['TMV', 'TMF'],
    ['LABD', 'LABU'],
    ['YANG', 'YINN'],
    ['DUST', 'NUGT'],
    ['JDST', 'JNUG'],
    ['GASX', 'GASL'],
    ['DRV', 'DRN'],
    ['RUSS', 'RUSL'],
    ['DRIP', 'GUSH'],
    ['SOXS', 'SOXL'],
    ['EDZ', 'EDC'],
    ['ERY', 'ERX'],
    ['FAZ', 'FAS'],
    ['SPXS', 'SPXL'],
    ['TZA', 'TNA'],
    ['TECS', 'TECL'],
    ['OILD', 'OILU'],
    ['SDOW', 'UDOW'],
    ['SQQQ', 'TQQQ'],
    ['SRTY', 'URTY'],
    ['SPXU', 'UPRO'],
    ['DWT', 'UWT'],
    ['DGLD', 'UGLD'],
    ['DGAZ', 'UGAZ'],
    ['DSLV', 'USLV'],
]