import datetime
import backtrader as bt
import backtrader.feeds as btfeed
import os
import tarfile
import io

DAILIES = [
'C:/Users/mcdof/Documents/kibot_data/stocks/daily/HPQ.txt',
'C:/Users/mcdof/Documents/kibot_data/stocks/daily/GE.txt',
'C:/Users/mcdof/Documents/kibot_data/stocks/daily/KO.txt',
'C:/Users/mcdof/Documents/kibot_data/stocks/daily/IBM.txt',
'C:/Users/mcdof/Documents/kibot_data/stocks/daily/DIS.txt',
'C:/Users/mcdof/Documents/kibot_data/stocks/daily/BA.txt',
'C:/Users/mcdof/Documents/kibot_data/stocks/daily/CAT.txt',
'C:/Users/mcdof/Documents/kibot_data/stocks/daily/ARNC.txt',
'C:/Users/mcdof/Documents/kibot_data/stocks/daily/AA.txt',
'C:/Users/mcdof/Documents/kibot_data/stocks/daily/DD.txt',
'C:/Users/mcdof/Documents/kibot_data/stocks/daily/MO.txt',
'C:/Users/mcdof/Documents/kibot_data/stocks/daily/MRO.txt',
'C:/Users/mcdof/Documents/kibot_data/stocks/daily/CNP.txt',
'C:/Users/mcdof/Documents/kibot_data/stocks/daily/MCD.txt',
'C:/Users/mcdof/Documents/kibot_data/stocks/daily/XOM.txt',
'C:/Users/mcdof/Documents/kibot_data/stocks/daily/JNJ.txt',
'C:/Users/mcdof/Documents/kibot_data/stocks/daily/MRK.txt',
'C:/Users/mcdof/Documents/kibot_data/stocks/daily/UTX.txt',
'C:/Users/mcdof/Documents/kibot_data/stocks/daily/FL.txt',
'C:/Users/mcdof/Documents/kibot_data/stocks/daily/CVX.txt',
'C:/Users/mcdof/Documents/kibot_data/stocks/daily/PG.txt',
'C:/Users/mcdof/Documents/kibot_data/stocks/daily/MMM.txt',
'C:/Users/mcdof/Documents/kibot_data/stocks/daily/AEP.txt',
'C:/Users/mcdof/Documents/kibot_data/stocks/daily/ED.txt',
'C:/Users/mcdof/Documents/kibot_data/stocks/daily/HON.txt',
'C:/Users/mcdof/Documents/kibot_data/stocks/daily/IP.txt',
'C:/Users/mcdof/Documents/kibot_data/stocks/daily/F.txt',
'C:/Users/mcdof/Documents/kibot_data/stocks/daily/DTE.txt',
'C:/Users/mcdof/Documents/kibot_data/stocks/daily/GT.txt',
'C:/Users/mcdof/Documents/kibot_data/stocks/daily/PFE.txt',
'C:/Users/mcdof/Documents/kibot_data/stocks/daily/EK.txt',
'C:/Users/mcdof/Documents/kibot_data/stocks/daily/TXN.txt',
'C:/Users/mcdof/Documents/kibot_data/stocks/daily/BMY.txt',
'C:/Users/mcdof/Documents/kibot_data/stocks/daily/WFC.txt',
'C:/Users/mcdof/Documents/kibot_data/stocks/daily/PBI.txt',
'C:/Users/mcdof/Documents/kibot_data/stocks/daily/HAL.txt',
'C:/Users/mcdof/Documents/kibot_data/stocks/daily/DE.txt',
'C:/Users/mcdof/Documents/kibot_data/stocks/daily/AVP.txt',
'C:/Users/mcdof/Documents/kibot_data/stocks/daily/EMR.txt',
'C:/Users/mcdof/Documents/kibot_data/stocks/daily/ETN.txt',
'C:/Users/mcdof/Documents/kibot_data/stocks/daily/PCG.txt',
'C:/Users/mcdof/Documents/kibot_data/stocks/daily/PEP.txt',
'C:/Users/mcdof/Documents/kibot_data/stocks/daily/WY.txt',
# 'C:/Users/mcdof/Documents/kibot_data/stocks/daily/ETR.txt',
# 'C:/Users/mcdof/Documents/kibot_data/stocks/daily/LLY.txt',
# 'C:/Users/mcdof/Documents/kibot_data/stocks/daily/USB.txt',
# 'C:/Users/mcdof/Documents/kibot_data/stocks/daily/WMT.txt',
# 'C:/Users/mcdof/Documents/kibot_data/stocks/daily/AXP.txt',
# 'C:/Users/mcdof/Documents/kibot_data/stocks/daily/DWDP.txt',
# 'C:/Users/mcdof/Documents/kibot_data/stocks/daily/DOW.txt',
# 'C:/Users/mcdof/Documents/kibot_data/stocks/daily/PNR.txt',
# 'C:/Users/mcdof/Documents/kibot_data/stocks/daily/MATX.txt',
# 'C:/Users/mcdof/Documents/kibot_data/stocks/daily/APOG.txt',
# 'C:/Users/mcdof/Documents/kibot_data/stocks/daily/NAV.txt',
# 'C:/Users/mcdof/Documents/kibot_data/stocks/daily/AVT.txt',
# 'C:/Users/mcdof/Documents/kibot_data/stocks/daily/NYT.txt',
# 'C:/Users/mcdof/Documents/kibot_data/stocks/daily/CHE.txt',
# 'C:/Users/mcdof/Documents/kibot_data/stocks/daily/ALE.txt',
# 'C:/Users/mcdof/Documents/kibot_data/stocks/daily/GFF.txt',
# 'C:/Users/mcdof/Documents/kibot_data/stocks/daily/SYY.txt',
# 'C:/Users/mcdof/Documents/kibot_data/stocks/daily/FRT.txt',
# 'C:/Users/mcdof/Documents/kibot_data/stocks/daily/EDE.txt',
# 'C:/Users/mcdof/Documents/kibot_data/stocks/daily/UIS.txt',
# 'C:/Users/mcdof/Documents/kibot_data/stocks/daily/PHI.txt',
# 'C:/Users/mcdof/Documents/kibot_data/stocks/daily/KR.txt',
# 'C:/Users/mcdof/Documents/kibot_data/stocks/daily/CL.txt',
# 'C:/Users/mcdof/Documents/kibot_data/stocks/daily/AET.txt',
# 'C:/Users/mcdof/Documents/kibot_data/stocks/daily/GD.txt',
# 'C:/Users/mcdof/Documents/kibot_data/stocks/daily/GAS.txt',
# 'C:/Users/mcdof/Documents/kibot_data/stocks/daily/LMT.txt',
# 'C:/Users/mcdof/Documents/kibot_data/stocks/daily/PEI.txt',
# 'C:/Users/mcdof/Documents/kibot_data/stocks/daily/BP.txt',
# 'C:/Users/mcdof/Documents/kibot_data/stocks/daily/SOGC.txt',

]

ALL_DATAS = [

    #"ES.txt"
    #'C:/Users/mcdof/Documents/kibot_data/cont_futures/1min/ES.txt',
        #   'C:/Users/mcdof/Documents/kibot_data/cont_futures/15min/GC.txt',
        #   'C:/Users/mcdof/Documents/kibot_data/cont_futures/15min/PA.txt',
        #    'C:/Users/mcdof/Documents/kibot_data/cont_futures/15min/PL.txt',
        #    'C:/Users/mcdof/Documents/kibot_data/cont_futures/15min/SI.txt',
        #    'C:/Users/mcdof/Documents/kibot_data/cont_futures/15min/HG.txt',
        #   'C:/Users/mcdof/Documents/kibot_data/cont_futures/15min/NN.txt',
        #   'C:/Users/mcdof/Documents/kibot_data/cont_futures/15min/NQ.txt',
        #   'C:/Users/mcdof/Documents/kibot_data/cont_futures/15min/NG.txt',
        #    'C:/Users/mcdof/Documents/kibot_data/cont_futures/15min/CL.txt',
        # #  # 'C:/Users/mcdof/Documents/kibot_data/cont_futures/15min/HO.txt',
        # # # # 'C:/Users/mcdof/Documents/kibot_data/cont_futures/15min/RB.txt',
        #    'C:/Users/mcdof/Documents/kibot_data/cont_futures/15min/TY.txt',
        #    'C:/Users/mcdof/Documents/kibot_data/cont_futures/15min/EU.txt',
        #    'C:/Users/mcdof/Documents/kibot_data/cont_futures/15min/JY.txt',
        #    'C:/Users/mcdof/Documents/kibot_data/cont_futures/15min/BP.txt',
        #    'C:/Users/mcdof/Documents/kibot_data/cont_futures/15min/CD.txt',
        #    'C:/Users/mcdof/Documents/kibot_data/cont_futures/15min/NE.txt',
        #    'C:/Users/mcdof/Documents/kibot_data/cont_futures/15min/AD.txt',
        #    'C:/Users/mcdof/Documents/kibot_data/cont_futures/15min/SF.txt',
        #    'C:/Users/mcdof/Documents/kibot_data/cont_futures/15min/DX.txt',
        #    'C:/Users/mcdof/Documents/kibot_data/cont_futures/15min/PX.txt',
        #    'C:/Users/mcdof/Documents/kibot_data/cont_futures/15min/GF.txt',
        #    'C:/Users/mcdof/Documents/kibot_data/cont_futures/15min/LE.txt',
        #    'C:/Users/mcdof/Documents/kibot_data/cont_futures/15min/HE.txt',
        #    'C:/Users/mcdof/Documents/kibot_data/cont_futures/15min/S.txt',
        #    'C:/Users/mcdof/Documents/kibot_data/cont_futures/15min/C.txt',
        #    'C:/Users/mcdof/Documents/kibot_data/cont_futures/15min/BO.txt',
        #    'C:/Users/mcdof/Documents/kibot_data/cont_futures/15min/SM.txt',
        #    'C:/Users/mcdof/Documents/kibot_data/cont_futures/15min/W.txt',
        #    'C:/Users/mcdof/Documents/kibot_data/cont_futures/15min/SB.txt',
        #    'C:/Users/mcdof/Documents/kibot_data/cont_futures/15min/KC.txt',
        #    'C:/Users/mcdof/Documents/kibot_data/cont_futures/15min/KW.txt',
        #    'C:/Users/mcdof/Documents/kibot_data/cont_futures/15min/CC.txt',
        #   'C:/Users/mcdof/Documents/kibot_data/cont_futures/15min/OJ.txt',
        #    'C:/Users/mcdof/Documents/kibot_data/cont_futures/15min/RR.txt',
        #    'C:/Users/mcdof/Documents/kibot_data/cont_futures/15min/O.txt',
        #    'C:/Users/mcdof/Documents/kibot_data/cont_futures/15min/LB.txt',
]

def get_quandl_data(symbol,exchange='CME',month='1'):
    csv_name = exchange + '_' + symbol.upper() + str(month) + '.csv'
    with tarfile.open('quandl_data.tar.gz','r') as f:
        member = f.getmember(csv_name)
        ret = f.extractfile(member)
        contents = ret.read().decode("utf-8")

        return btfeed.GenericCSVData(dataname=io.StringIO(contents),
                              dtformat='%Y-%m-%d',
                              name=symbol,
                              timeframe=bt.TimeFrame.Ticks,
                              fromdate=datetime.datetime(2009, 1, 1),
                              todate=datetime.datetime(2010, 1, 1),
                              datetime=0,
                              open=1,
                              high=2,
                              low=3,
                              close=4,
                              volume=7,
                              openinterest=8,
                              plot=False
                              )


def add_data(cerebro):
    for txt in DAILIES: #ALL_DATAS:
        data = btfeed.GenericCSVData(dataname=txt,
                                     dtformat='%m/%d/%Y',
                                     #tmformat='%H:%M',
                                     name = os.path.splitext(os.path.basename(txt))[0],
                                     timeframe=bt.TimeFrame.Ticks,
                                     fromdate=datetime.datetime(1900, 1, 1),
                                     todate=datetime.datetime(2019, 12, 1),
                                     datetime=0,
                                     time=-1,
                                     open=1,
                                     high=2,
                                     low=3,
                                     close=4,
                                     volume=5,
                                     openinterest=-6,
                                     plot=False
                                     )
        cerebro.adddata(data)